export const fontList = {
    "02UtsukushiMincho": "02うつくし明朝体",
    "03SmartFontUI": "03スマートフォントUI",
    "07LightNovelPOP": "07ラノベPOP",
    "07NikumaruFont": "07にくまるフォント",
    "A P-OTF A1Gothic Std": "A P-OTF A1ゴシック Std",
    "A P-OTF A1Gothic Std B": "A P-OTF A1ゴシック Std B",
    "A P-OTF Shimanami StdN": "A P-OTF しまなみ StdN",
    "A P-OTF Shimanami StdN R": "A P-OTF しまなみ StdN R",
    "A P-OTF HappyN+ ProN": "A P-OTF ハッピーN+ ProN",
    "A P-OTF HappyN+ ProN B": "A P-OTF ハッピーN+ ProN B",
    "A P-OTF KamoLime+ ProN": "A P-OTF カモライム+ ProN",
    "A P-OTF KamoLime+ ProN B": "A P-OTF カモライム+ ProN B",
    "A P-OTF SuiryuAtlas StdN": "A P-OTF 翠流アトラス StdN",
    "A P-OTF SuiryuAtlas StdN B": "A P-OTF 翠流アトラス StdN B",
    "A P-OTF Shuei MaruGo Std": "A P-OTF 秀英丸ゴシック Std",
    "A P-OTF Shuei MaruGo Std B": "A P-OTF 秀英丸ゴシック Std B",
    "A P-OTF Shuei NijimiMin StdN": "A P-OTF 秀英にじみ明朝 StdN",
    "A P-OTF Shuei NijimiMin StdN L": "A P-OTF 秀英にじみ明朝 StdN L",
    "A P-OTF SuiryuDecoroman StdN": "A P-OTF 翠流デコロマン StdN",
    "A P-OTF SuiryuDecoroman StdN U": "A P-OTF 翠流デコロマン StdN U",
    "A P-OTF SuiryuNeoroman StdN": "A P-OTF 翠流ネオロマン StdN",
    "A P-OTF SuiryuNeoroman StdN U": "A P-OTF 翠流ネオロマン StdN U",
    "A-OTF A1 Mincho Std": "A-OTF A1明朝 Std",
    "A-OTF A1 Mincho Std Bold": "A-OTF A1明朝 Std Bold",
    "A-OTF UD Shin Go Pro": "A-OTF UD新ゴ Pro",
    "A-OTF UD Shin Go Pro B": "A-OTF UD新ゴ Pro B",
    "A-OTF Shin Go Pr5": "A-OTF 新ゴ Pr5",
    "A-OTF Shin Go Pr5 B": "A-OTF 新ゴ Pr5 B",
    "A-OTF Shin Go Pr6": "A-OTF 新ゴ Pr6",
    "A-OTF Shin Go Pr6N": "A-OTF 新ゴ Pr6N",
    "A-OTF Shin Go Pro": "A-OTF 新ゴ Pro",
    "A-OTF Futo Go B101 Pro": "A-OTF 太ゴB101 Pro",
    "A-OTF Futo Go B101 Pro Bold": "A-OTF 太ゴB101 Pro Bold",
    "A-OTF Jun Pro": "A-OTF じゅん Pro",
    "A-OTF Jun Pro 101": "A-OTF じゅん Pro 101",
    "A-OTF Shin Maru Go Pro": "A-OTF 新丸ゴ Pro",
    "A-OTF Shin Maru Go Pro B": "A-OTF 新丸ゴ Pro B",
    "A-OTF Midashi Go MB1 Std": "A-OTF 見出ゴMB1 Std",
    "A-OTF Midashi Go MB1 Std DeBold": "A-OTF 見出ゴMB1 Std DeBold",
    "A-OTF Midashi Go MB31 Pro": "A-OTF 見出ゴMB31 Pro",
    "A-OTF Midashi Go MB31 Pro MB31": "A-OTF 見出ゴMB31 Pro MB31",
    "A-OTF Folk Pro": "A-OTF フォーク Pro",
    "A-OTF Folk Pro B": "A-OTF フォーク Pro B",
    "A-OTF Midashi Min MA1 Std": "A-OTF 見出ミンMA1 Std",
    "A-OTF Midashi Min MA1 Std Bold": "A-OTF 見出ミンMA1 Std Bold",
    "A-OTF Midashi Min MA31 Pr5": "A-OTF 見出ミンMA31 Pr5",
    "A-OTF Midashi Min MA31 Pr5 MA31": "A-OTF 見出ミンMA31 Pr5 MA31",
    "A-OTF CapieN Std": "A-OTF キャピーN Std",
    "A-OTF CapieN Std B": "A-OTF キャピーN Std B",
    "A-OTF Maru Folk Pro": "A-OTF 丸フォーク Pro",
    "A-OTF Maru Folk Pro B": "A-OTF 丸フォーク Pro B",
    "A-OTF Ryumin Pro": "A-OTF リュウミン Pro",
    "A-OTF Ryumin Pro B-KL": "A-OTF リュウミン Pro B-KL",
    "A-OTF Gothic BBB Pro": "A-OTF 中ゴシックBBB Pro",
    "A-OTF Gothic BBB Pro Medium": "A-OTF 中ゴシックBBB Pro Medium",
    "BIZ UDPMincho": "BIZ UDP明朝",
    "BIZ UDMincho": "BIZ UD明朝",
    "HGPSoeiKakugothicUB": "HGP創英角ｺﾞｼｯｸUB",
    "HGSSoeiKakugothicUB": "HGS創英角ｺﾞｼｯｸUB",
    "HGSoeiKakugothicUB": "HG創英角ｺﾞｼｯｸUB",
    "M+A1 black 10/1.2": "M+A1",
    "Mplus 1p Bold": "Mplus 1p Bold",
    "Murecho Thin": "Murecho",
    "Noto Sans JP": "Noto Sans JP",
    "Noto Serif JP": "Noto Serif JP",
    "RA HanaBotan Std": "RA花牡丹 Std",
    "RA HanaBotan Std DB": "RA花牡丹 Std DB",
    "Ro GSan Serif Std": "RoG2サンセリフStd",
    "Ro GSan Serif Std B": "RoG2サンセリフStd-B",
    "Rounded Mplus 1c": "Rounded Mplus 1c",
    "Ro NOW Std": "RoナウStd",
    "Ro NOW Std GB": "RoナウStd-GB",
    "Ro Pokkru Std": "RoぽっくるStd",
    "Ro Pokkru Std B": "RoぽっくるStd-B",
    "Ro Brush Std": "RoぶらっしゅStd",
    "Ro Brush Std U": "RoぶらっしゅStd-U",
    "TBEcho Std": "TBエコー Std",
    "TBEcho Std B": "TBエコー Std B",
    "TBOrb Std": "TBオーブ Std",
    "TBOrb Std R": "TBオーブ Std R",
    "TBGothicB Std": "TBゴシックB Std",
    "TBGothicB Std C6": "TBゴシックB Std C6",
    "TBGothicDB Std": "TBゴシックDB Std",
    "TBGothicDB Std C6": "TBゴシックDB Std C6",
    "TBGothicL Std": "TBゴシックL Std",
    "TBGothicL Std C6": "TBゴシックL Std C6",
    "TBGothicR Std": "TBゴシックR Std",
    "TBGothicR Std C6": "TBゴシックR Std C6",
    "TBGothicSL Std": "TBゴシックSL Std",
    "TBGothicSL Std C6": "TBゴシックSL Std C6",
    "U-OTF Futo Min A101 Upr": "U-OTF 太ミンA101 Upr",
    "U-OTF Futo Min A101 Upr Bold": "U-OTF 太ミンA101 Upr Bold",
    "UDDigiKyokasho Std": "UDデジタル教科書体 Std",
    "UDDigiKyokasho Std B": "UDデジタル教科書体 Std B",
    "Tsukushi A Round Gothic": "筑紫A丸ゴシック",
    "Tsukushi A Round Gothic Bold": "筑紫A丸ゴシック ボールド",
    "Tsukushi B Round Gothic": "筑紫B丸ゴシック",
    "Tsukushi B Round Gothic Bold": "筑紫B丸ゴシック ボールド",
    "YuMincho +36p Kana": "游明朝体+36ポかな",
    "YuMincho +36p Kana Demibold": "游明朝体+36ポかな デミボールド",
    "YuKyokasho New Yoko": "游教科書体 横用",
    "YuKyokasho New": "游教科書体",
    "YuKyokasho New Yoko B": "游教科書体 New 横用 B",
    "YuKyokasho New B": "游教科書体 New B",
    "Hiragino UD Sans Std": "ヒラギノUD角ゴ Std",
    "Hiragino UD Sans Std W3": "ヒラギノUD角ゴ Std W3",
    "Hiragino Kaku Gothic Pro": "ヒラギノ角ゴ Pro",
    "Hiragino Kaku Gothic Pro W3": "ヒラギノ角ゴ Pro W3",
    "Hiragino Maru Gothic Pro": "ヒラギノ丸ゴ Pro",
    "Hiragino Maru Gothic Pro W4": "ヒラギノ丸ゴ Pro W4",
    "Hiragino Mincho Pro": "ヒラギノ明朝 Pro",
    "Hiragino Mincho Pro W3": "ヒラギノ明朝 Pro W3",
    "Hiragino Kaku Gothic ProN": "ヒラギノ角ゴ ProN",
    "Hiragino Maru Gothic ProN": "ヒラギノ丸ゴ ProN",
    "Hiragino Mincho ProN": "ヒラギノ明朝 ProN",
    "Hiragino Kaku Gothic Std": "ヒラギノ角ゴ Std",
    "Hiragino Mincho Std": "ヒラギノ明朝 Std",
    "Hiragino Kaku Gothic StdN": "ヒラギノ角ゴ StdN",
    "HannariMincho": "はんなり明朝",
    "Honoka Shin Mincho": "ほのか新明朝",
    "Sawarabi Mincho": "さわらび明朝",
    "Shippori Mincho": "しっぽり明朝",
    "Toppan Bunkyu Mincho": "凸版文久明朝",
    "YuGothic": "游ゴシック体",
    "Shippori Mincho B1": "しっぽり明朝B1",
    "Gen Jyuu GothicX": "源柔ゴシックX",
    "Gen Jyuu Gothic X Monospace": "源柔ゴシックX等幅",
    "Source Han Code JP": "源ノ角ゴシック Code JP",
    "Mochiy Pop E": "モッチーポップ E",
    "RocknRoll One": "ロックンロール One",
    "HarenosoraMincho": "はれのそら明朝",
    "MisterGray": "ミスターグレイ",
    "azuki_font": "あずきフォント",
    "Koburina Gothic Std": "こぶりなゴシック Std",
    "Toppan Bunkyu Gothic": "凸版文久ゴシック",
    "Corporate Logo ver2": "コーポレート・ロゴ ver2",
    "Hiragino Sans": "ヒラギノ角ゴシック",
    "Toppan Bunkyu Midashi Mincho": "凸版文久見出し明朝",
    "Honoka Antique-Kaku": "ほのかアンティーク角",
    "Toppan Bunkyu Midashi Gothic": "凸版文久見出しゴシック",
    "Corporate Logo Rounded ver2": "コーポレート・ロゴ（ラウンド） ver2"
  };
